### PR TITLE
Optional HTML footer with stats/diagnostics

### LINKED ISSUE #154: Set HTTP Response Header to show cached response
Hello Till,

i really appreciate your work on this plugin and i already use it successfully on my development page.
However i have a suggestion: When uing the plugin, you can clearly see which reponse was served by redis, as the speed is by far higher. However, a HTTP-Header indicating a cached response would be great.
Do you have an idea how to implement this? Do you think this could be included in this plugin?
Suggestion:
X-Redis-Cache: HIT
X-Redis-Cache: MISS
X-Redis-Cache: BYPASS (If that is possible/necessary)

What do you think?

Best regards!

### PR DESCRIPTION
**Pull request by tillkruss**
- [x] Show stats when `WP_DEBUG` is enabled
- [ ] Show stats via `WP_REDIS_*` constant
- [ ] Show stats via secure URL parameter
- [ ] Split hits/missing: Redis and in-memory
- [ ] Refine comment template (one liner?)

Resolves #154

### CODE REVIEW

**Comment by lkraav** [comment]
I wonder if integration with Query Monitor is in scope here? cc @johnbillion

**Comment by tillkruss** [comment]
@lkraav: We should probably just add support for this: https://github.com/johnbillion/query-monitor/blob/3402629d84ad2ce6ede80f60762b68fe319945cb/output/html/overview.php#L186-L210

@johnbillion: Unless we want to add a dedicated section for the Object Cache with heaps of details, such as cache groups, total size, etc.

**Comment by johnbillion** [comment]
The reason QM doesn't display detailed info about the cache stats is because, as you'll probably know, the WP cache API doesn't provide abstraction for this, so each cache controller stores its stats in a different place.

Let me know if you need me to add anything to QM to enable more detailed stats from the cache controller. I don't think there's a hook in there at the moment to add data to the overview, but you can add your own panel.

**Comment by tillkruss** [comment]
@johnbillion: Yeah, the Pro version adds it's own panel.

How do you feel about about setting a standard for an object cache panel? QM already uses the `stats` and `cache_hit_percentage` anyhow.

**Comment by johnbillion** [comment]
I like that idea. QM could define an object cache panel and cache controllers push their data into it regardless of how they internally store stats.

**Comment by tillkruss** [comment]
Let's move this to https://github.com/johnbillion/query-monitor/issues/518/.

**Comment by tillkruss** [comment]
Closing in favor of #167.

**Comment by tillkruss** [comment]
See https://github.com/tillkruss/redis-cache/issues/154#issuecomment-636100823 for a summary of footer comments on other caching plugins.

**Pull request closed without merging**
