### PR TITLE
cleans up cluttered cron schedule

### PR DESCRIPTION
**Pull request by sawanoboly**
https://github.com/tillkruss/redis-cache/issues/131#issuecomment-558905122

### CODE REVIEW

**Comment by tillkruss** [comment]
Thanks!

**Comment by sawanoboly** [comment]
release new version, please. @tillkruss

**Comment by tillkruss** [comment]
Not for such a minor change, no.

**Comment by sawanoboly** [comment]
@tillkruss 
I am hosting using WordPress.
The worst cronjob that only outputs an error is registered in all customer environments.

**Comment by sawanoboly** [comment]
You should be aware of what you have done and try to recover responsibly.

**Comment by tillkruss** [comment]
I didn’t get any error report.

**Comment by sawanoboly** [comment]
Originally, this change is a fix that should be included in 1.5.4. Delete unnecessary wp-cron entries.

**Comment by tillkruss** [comment]
Unless you report the actual error that’s occurring because of the schedule event, I consider this topic closed.

**Pull request merged**
